volumes:
  pgdata:
  webdata:

services:
  postgres:
    container_name: shroom-postgres
    build: ./postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  shroom-webserver:
    container_name: shroom-webserver
    build: ./shroom-webserver
    restart: always
    ports:
      - 5000:5000
    environment:
      SHROOM_DB_NAME: ${POSTGRES_DB_NAME}
      SHROOM_DB_USER: ${POSTGRES_DB_USER}
      PGPASSWORD: ${PGPASSWORD}
      SHROOM_SB_TABLE_NAME: ${POSTGRES_SB_TABLE_NAME}
      SHROOM_LB_TABLE_NAME: ${POSTGRES_LB_TABLE_NAME}
      WEBSERVER_PORT: ${WEBSERVER_PORT}
    volumes:
      - webdata:/server
      - ./shroom-webserver/server.py:/server/server.py
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"
      # Match incoming requests on a specific hostname
      - "traefik.http.routers.shroomweb.rule=Host(`shroomweb.${ROOT_DOMAIN}`)"
      # Assign the router to a named Traefik service
      - "traefik.http.routers.shroomweb.service=sabnzbd"
      # Use the 'websecure' (HTTPS) entry point
      - "traefik.http.routers.shroomweb.entrypoints=websecure"
      # Define the internal container port for routing
      - "traefik.http.services.shroomweb.loadbalancer.server.port=5000"
      # Enable TLS on this router
      - "traefik.http.routers.shroomweb.tls=true"
      # Use Let's Encrypt for certificate management
      - "traefik.http.routers.shroomweb.tls.certresolver=letsencrypt"
      # Pass the original Host header to the container
      - "traefik.http.services.shroomweb.loadbalancer.passhostheader=true"
      # Apply a compression middleware
      - "traefik.http.routers.shroomweb.middlewares=compresstraefik"
      # Define settings for the compression middleware
      - "traefik.http.middlewares.compresstraefik.compress=true"
      # Specify which Docker network Traefik should use for routing
      - "traefik.docker.network=traefik-network"
  shroom-mkproject:
    build: ./shroomin-mkproject
    environment:
      SHROOM_DB_NAME: ${POSTGRES_DB_NAME}
      SHROOM_DB_USER: ${POSTGRES_DB_USER}
      PGPASSWORD: ${PGPASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
#Optional but provides automated checking with NelS's sizecheck program
  shroom-checker:
    container_name: shroom-checker
    build: ./checker
    restart: always
    environment:
      SHROOM_DB_NAME: ${POSTGRES_DB_NAME}
      SHROOM_DB_USER: ${POSTGRES_DB_USER}
      PGPASSWORD: ${PGPASSWORD}
      SHROOM_SB_TABLE_NAME: ${POSTGRES_SB_TABLE_NAME}
      SHROOM_LB_TABLE_NAME: ${POSTGRES_LB_TABLE_NAME}
      SHROOM_CHECKER_THREADS: ${CHECKER_THREADS}
    depends_on:
      postgres:
        condition: service_healthy
#Optional
  shroom-grafana:
    container_name: shroom-grafana
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
    - 3000:3000
  shroom-bot:
    build: ./shroom-bot
    environment:
    SHROOM_BOT_DISCORD_TOKEN: ${SHROOM_BOT_DISCORD_TOKEN}
    SHROOM_BOT_API_KEY: ${SHROOM_BOT_API_KEY}